# Generated by Django 5.0 on 2024-01-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='collection')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products')),
                ('price', models.PositiveIntegerField(default=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('food_type', models.IntegerField(choices=[(0, 'Egg'), (1, 'Eggless')], default=0)),
                ('qty', models.FloatField(blank=True, default=50.0, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
